#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    ddev-hello-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^ddev-hello\.ddev\.site$`)
      
      service: "ddev-hello-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ddev-hello-redirectHttps"
    ddev-hello-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^ddev-hello\.ddev\.site$`)
      
      service: "ddev-hello-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ddev-hello-redirectHttps"
    ddev-hello-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^ddev-hello\.ddev\.site$`)
      
      service: "ddev-hello-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ddev-hello-redirectHttps"
    
    
    
    ddev-hello-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^ddev-hello\.ddev\.site$`)
      
      service: "ddev-hello-web-80"
      ruleSyntax: v3
      
      tls: true
      
    ddev-hello-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^ddev-hello\.ddev\.site$`)
      
      service: "ddev-hello-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    ddev-hello-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^ddev-hello\.ddev\.site$`)
      
      service: "ddev-hello-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    ddev-hello-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    ddev-hello-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-ddev-hello-web:80
        
    ddev-hello-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-ddev-hello-web:8025
        
    
    
    ddev-hello-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-ddev-hello-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/ddev-hello.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/ddev-hello.key